<a href="https://colab.research.google.com/github/mundundan-star/online-retail-customer-analytics/blob/main/Customer_Segments_Profiling_and_Statistical_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
from sqlalchemy import create_engine, text, inspect
from google.colab import userdata

engine = create_engine(userdata.get("NEON_DATABASE_URL"))

query = """
SELECT *
FROM v_segmented_data
"""

df = pd.read_sql(text(query), con = engine)
print("Preview of data pulled from Postgres database")
df.head()

Preview of data pulled from Postgres database

,CustomerID,Recency,Frequency,TotalRevenue,Tenure,ProductDiversity,KSegment
0,12346.0,325,1,77183.60,0,1,1
1,12347.0,129,5,2790.86,238,82,2
2,12348.0,248,3,1487.24,110,22,0
3,12350.0,310,1,334.40,0,17,0
4,12352.0,262,4,1561.81,34,26,0

In [9]:
df.groupby("KSegment").agg(
  customer_count = ("CustomerID", "count"),
  percentage = ("CustomerID", lambda x : f"{len(x)/ len(df) * 100:.1f} %"),
  median_revenue = ("TotalRevenue", "median"),
  median_tenure = ("Tenure", "median"),
  median_recency = ("Recency", "median"),
  median_frequency = ("Frequency", "median"),
  median_diversity = ("ProductDiversity", "median")).reset_index()

,KSegment,customer_count,percentage,median_revenue,median_tenure,median_recency,median_frequency,median_diversity
0,0,2018,60.8 %,312.30,0.0,220.0,1.0,18.0
1,1,20,0.6 %,45618.62,261.5,107.0,29.5,368.5
2,2,1279,38.6 %,1501.82,186.0,127.0,4.0,66.0

In [10]:
persona_mapping = {
    0: "One Time Acquaintances",
    1: "High-Value Elite",
    2: "Loyal Steady Shoppers"
}
df['Persona'] = df['KSegment'].map(persona_mapping)