<a href="https://colab.research.google.com/github/mundundan-star/online-retail-customer-analytics/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import userdata

from sqlalchemy import create_engine, text

engine = create_engine(userdata.get("NEON_DATABASE_URL"))

# Pulling data before the churn cut off point
query = """
SELECT "CustomerID",
    SUM("Revenue") AS "TotalRevenue",
    MIN("InvoiceDate") AS "FirstPurchase",
    MAX("InvoiceDate") AS "LastPurchase",
    MAX("InvoiceDate") - MIN("InvoiceDate") AS "Tenure",
    (SELECT MAX("InvoiceDate")
    FROM v_clean_sales_analytics) - MAX("InvoiceDate") AS "Recency",
    COUNT(DISTINCT "StockCode") AS "ProductDiversity",
    COUNT(DISTINCT "InvoiceDate") AS "Frequency",
    TO_CHAR(MIN("InvoiceDate"), 'YYYY-MM') AS "CohortMonth"
FROM v_clean_sales_analytics
WHERE "InvoiceDate" <= '2011-08-31'
GROUP BY "CustomerID"
"""

df = pd.read_sql(text(query), con = engine, parse_dates = "InvoiceDate")
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3317 entries, 0 to 3316
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        3317 non-null   float64
 1   TotalRevenue      3317 non-null   float64
 2   FirstPurchase     3317 non-null   object
 3   LastPurchase      3317 non-null   object
 4   Tenure            3317 non-null   int64
 5   Recency           3317 non-null   int64
 6   ProductDiversity  3317 non-null   int64
 7   Frequency         3317 non-null   int64
 8   CohortMonth       3317 non-null   object
dtypes: float64(2), int64(4), object(3)
memory usage: 233.4+ KB
None

,CustomerID,TotalRevenue,FirstPurchase,LastPurchase,Tenure,Recency,ProductDiversity,Frequency,CohortMonth
0,12346.0,77183.60,2011-01-18,2011-01-18,0,325,1,1,2011-01
1,12347.0,2790.86,2010-12-07,2011-08-02,238,129,82,5,2010-12
2,12348.0,1487.24,2010-12-16,2011-04-05,110,248,22,3,2010-12
3,12350.0,334.40,2011-02-02,2011-02-02,0,310,17,1,2011-02
4,12352.0,1561.81,2011-02-16,2011-03-22,34,262,26,4,2011-02

           Revenue
             count       sum
CustomerID
12346.0          1  77183.60
12347.0        124   2790.86
12348.0         28   1487.24
12350.0         17    334.40
12352.0         38   1561.81
...            ...       ...
18280.0         10    180.60
18281.0          7     80.82
18282.0          7    100.21
18283.0        377    951.93
18287.0         29    765.28

[3317 rows x 2 columns]